refactor: use reusable action instead of composite

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,154 +1,152 @@
 name: Picasso V2
 description: 'Picasso is a tool for building Open edX images. These images are used to launch Open edX environments for both production and development.'
-inputs:
-  STRAIN_REPOSITORY:
-    description: '...'
-    required: true
-  STRAIN_REPOSITORY_BRANCH:
-    description: '...'
-    required: true
-  STRAIN_PATH:
-    description: '...'
-    required: true
-  SERVICE:
-    description: '...'
-    required: true
-  DOCKERHUB_USERNAME:
-    description: '...'
-    required: true
-  DOCKERHUB_PASSWORD:
-    description: '...'
-    required: true
-  REPO_DEPLOYMENT_KEY:
-    description: '...'
-    required: true
 
-runs:
-  using: 'composite'
-  steps:
-  - name: Login in DockerHub
-    uses: docker/login-action@v3
-    with:
-      username: ${{ inputs.DOCKERHUB_USERNAME }}
-      password: ${{ inputs.DOCKERHUB_PASSWORD }}
+on:
+  workflow_call:
+    inputs:
+      STRAIN_REPOSITORY:
+        description: 'The repository URL for strains'
+        required: true
+        type: string
+      STRAIN_REPOSITORY_BRANCH:
+        description: 'The branch of the repository to checkout'
+        required: true
+        type: string
+      STRAIN_PATH:
+        description: 'The path within the repository for strains'
+        required: true
+        type: string
+      SERVICE:
+        description: 'The service name to build'
+        required: true
+        type: string
+    secrets:
+      DOCKERHUB_USERNAME:
+        description: 'DockerHub username for login'
+        required: true
+      DOCKERHUB_PASSWORD:
+        description: 'DockerHub password for login'
+        required: true
+      REPO_DEPLOYMENT_KEY:
+        description: 'Deployment key for repository checkout'
+        required: true
 
-  - name: Checkout strains repository
-    uses: actions/checkout@v2
-    with:
-      repository: ${{ inputs.STRAIN_REPOSITORY }}
-      ref: ${{ inputs.STRAIN_REPOSITORY_BRANCH }}
-      token: ${{ inputs.REPO_DEPLOYMENT_KEY }}
+jobs:
+  build:
+    runs-on: ubuntu-latest
 
-  - name: Get Global Variables
-    shell: bash
-    working-directory: ${{ inputs.STRAIN_PATH }}
-    run: |
-      pwd
-      if [ ! -e "./config.yml" ]; then
-        echo "ERROR: file config.yml doesn't exist"
-        exit 1 # terminate and indicate error
-      fi
+    steps:
+      - name: Login to DockerHub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-      # Initialize variables
-      strain_name=""
-      strain_tutor_version=""
+      - name: Checkout strains repository
+        uses: actions/checkout@v2
+        with:
+          repository: ${{ inputs.STRAIN_REPOSITORY }}
+          ref: ${{ inputs.STRAIN_REPOSITORY_BRANCH }}
+          token: ${{ secrets.REPO_DEPLOYMENT_KEY }}
 
-      # Read config.yml line by line
-      while IFS= read -r line || [[ -n $line ]]; do
-        if [[ "$line" == *":"* ]]; then
-          name=$(echo "$line" | cut -d ":" -f1)
-          value=$(echo "$line" | cut -d ":" -f2- | awk '{$1=$1};1' | tr -d '\r')
+      - name: Set TVM project name and version
+        shell: bash
+        working-directory: ${{ inputs.STRAIN_PATH }}
+        run: |
+          if [ ! -e "./config.yml" ]; then
+            echo "ERROR: file config.yml doesn't exist"
+            exit 1 # terminate and indicate error
+          fi
 
-          case $name in
-            *"TUTOR_APP_NAME"*)
-              strain_name=$value
-              ;;
-            *"TUTOR_VERSION"*)
-              strain_tutor_version=$value
-              ;;
-          esac
-        fi
-      done < "config.yml"
+          # Initialize variables
+          strain_name=""
+          strain_tutor_version=""
 
-      # Check if variables are set
-      if [ -z "$strain_name" ]; then
-        echo "ERROR: TUTOR_APP_NAME not found in the given config.yml" >&2
-        exit 1
-      fi
+          # Read config.yml line by line
+          while IFS= read -r line || [[ -n $line ]]; do
+            if [[ "$line" == *":"* ]]; then
+              name=$(echo "$line" | cut -d ":" -f1)
+              value=$(echo "$line" | cut -d ":" -f2- | awk '{$1=$1};1' | tr -d '\r')
 
-      if [ -z "$strain_tutor_version" ]; then
-        echo "ERROR: TUTOR_VERSION not found in the given config.yml" >&2
-        exit 1
-      fi
+              case $name in
+                *"TUTOR_APP_NAME"*)
+                  strain_name=$value
+                  ;;
+                *"TUTOR_VERSION"*)
+                  strain_tutor_version=$value
+                  ;;
+              esac
+            fi
+          done < "config.yml"
 
-      echo "TUTOR_APP_NAME=${strain_name}" >> $GITHUB_ENV
-      echo "TUTOR_VERSION=${strain_tutor_version}" >> $GITHUB_ENV
+          # Check if variables are set
+          if [ -z "$strain_name" ]; then
+            echo "ERROR: TUTOR_APP_NAME not found in the given config.yml" >&2
+            exit 1
+          fi
 
-  - name: Install dependencies and activate virtualenv
-    shell: bash
-    run: |
-      pwd
-      python -m venv venv
-      python -m pip install --upgrade pip
-      . venv/bin/activate
-      pip install git+https://github.com/eduNEXT/tvm.git
-      echo $PATH
-      echo PATH=$PATH >> $GITHUB_ENV
+          if [ -z "$strain_tutor_version" ]; then
+            echo "ERROR: TUTOR_VERSION not found in the given config.yml" >&2
+            exit 1
+          fi
 
-  - name: Install TVM
-    shell: bash
-    working-directory: ${{ inputs.STRAIN_PATH }}
-    run: |
-      tvm install $TUTOR_VERSION
-      tvm project init $TUTOR_APP_NAME $TUTOR_VERSION
+          echo "TUTOR_APP_NAME=${strain_name}" >> $GITHUB_ENV
+          echo "TUTOR_VERSION=${strain_tutor_version}" >> $GITHUB_ENV
 
-      # This command copies all the files and folders
-      # from the repository STRAIN_PATH to the recently above created TVM PROJECT folder
-      cp -r $(ls --ignore=$TUTOR_APP_NAME) $TUTOR_APP_NAME/
+      - name: Install dependencies and activate virtualenv
+        shell: bash
+        run: |
+          python -m venv venv
+          python -m pip install --upgrade pip
+          . venv/bin/activate
+          pip install git+https://github.com/eduNEXT/tvm.git
+          echo $PATH
+          echo PATH=$PATH >> $GITHUB_ENV
 
-  - name: Configure TVM Project
-    shell: bash
-    working-directory: ${{ inputs.STRAIN_PATH }}/${{ env.TUTOR_APP_NAME }}
-    run: |
-      . .tvm/bin/activate
-      tutor config save
+      - name: Configure TVM project
+        shell: bash
+        working-directory: ${{ inputs.STRAIN_PATH }}
+        run: |
+          tvm install $TUTOR_VERSION
+          tvm project init $TUTOR_APP_NAME $TUTOR_VERSION
 
-  - name: Execute extra commands
-    shell: bash
-    working-directory: ${{ inputs.STRAIN_PATH }}/${{ env.TUTOR_APP_NAME }}
-    run: |
-      . .tvm/bin/activate
-      tutor plugins update
+          # This command copies all the files and folders
+          # from the repository STRAIN_PATH to the recently above created TVM PROJECT folder
+          cp -r $(ls --ignore=$TUTOR_APP_NAME) $TUTOR_APP_NAME/
 
-      major_version=$(pip show tutor | grep Version | awk '{print $2}' | cut -d'.' -f1)
-      distro_version=$(
-          git ls-remote --tags https://github.com/eduNEXT/tutor-contrib-edunext-distro \
-          | grep -E "$major_version\\.[0-9]+\\.[0-9]+$" \
-          | tail -n 1 \
-          | awk -F'/' '{print $NF}' \
-      )
+      - name: Enable distro plugin
+        shell: bash
+        working-directory: ${{ inputs.STRAIN_PATH }}/${{ env.TUTOR_APP_NAME }}
+        run: |
+          . .tvm/bin/activate
+          tutor plugins update
 
-      pip install git+https://github.com/eduNEXT/tutor-contrib-edunext-distro@$distro_version
+          major_version=$(pip show tutor | grep Version | awk '{print $2}' | cut -d'.' -f1)
+          distro_version=$(
+              git ls-remote --tags https://github.com/eduNEXT/tutor-contrib-edunext-distro \
+              | grep -E "$major_version\\.[0-9]+\\.[0-9]+$" \
+              | tail -n 1 \
+              | awk -F'/' '{print $NF}' \
+          )
 
-      tutor plugins list
-      tutor plugins enable distro
+          pip install git+https://github.com/eduNEXT/tutor-contrib-edunext-distro@$distro_version
 
-      # syntax_validation=$(tutor distro syntax-validator)
+          tutor plugins list
+          tutor plugins enable distro
 
-      # # Fails if the returned value doesn't contain the word 'Success'
-      # if [ -n "$syntax_validation" ] && ! echo "$syntax_validation" | grep -q "Success"; then
-      #     echo "SYNTAX ERROR was found in the given config.yml: '$syntax_validation'" >&2
-      #     exit 1
-      # fi
+      - name: Execute extra commands
+        shell: bash
+        working-directory: ${{ inputs.STRAIN_PATH }}/${{ env.TUTOR_APP_NAME }}
+        run: |
+          . .tvm/bin/activate
+          tutor distro run-extra-commands
 
-      tutor distro run-extra-commands
-      tutor config save
-
-  - name: Build service
-    shell: bash
-    working-directory: ${{ inputs.STRAIN_PATH }}/${{ env.TUTOR_APP_NAME }}
-    env:
-      SERVICE: ${{ inputs.SERVICE }}
-    run: |
-      . .tvm/bin/activate
-      tutor images build $SERVICE --no-cache
+      - name: Build service image with no cache
+        shell: bash
+        working-directory: ${{ inputs.STRAIN_PATH }}/${{ env.TUTOR_APP_NAME }}
+        env:
+          SERVICE: ${{ inputs.SERVICE }}
+        run: |
+          . .tvm/bin/activate
+          tutor config save
+          tutor images build $SERVICE --no-cache
