temp: comment syntax validator for now

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -122,10 +122,10 @@ runs:
 
       major_version=$(pip show tutor | grep Version | awk '{print $2}' | cut -d'.' -f1)
       distro_version=$(
-          git ls-remote --tags https://github.com/eduNEXT/tutor-contrib-edunext-distro \\
-          | grep -E "$major_version\\.[0-9]+\\.[0-9]+$" \\
-          | tail -n 1 \\
-          | awk -F'/' '{print $NF}' \\
+          git ls-remote --tags https://github.com/eduNEXT/tutor-contrib-edunext-distro \
+          | grep -E "$major_version\\.[0-9]+\\.[0-9]+$" \
+          | tail -n 1 \
+          | awk -F'/' '{print $NF}' \
       )
 
       pip install git+https://github.com/eduNEXT/tutor-contrib-edunext-distro@$distro_version
@@ -133,13 +133,13 @@ runs:
       tutor plugins list
       tutor plugins enable distro
 
-      syntax_validation=$(tutor distro syntax-validator)
+      # syntax_validation=$(tutor distro syntax-validator)
 
-      # Fails if the returned value doesn't contain the word 'Success'
-      if [ -n "$syntax_validation" ] && ! echo "$syntax_validation" | grep -q "Success"; then
-          echo "SYNTAX ERROR was found in the given config.yml: '$syntax_validation'" >&2
-          exit 1
-      fi
+      # # Fails if the returned value doesn't contain the word 'Success'
+      # if [ -n "$syntax_validation" ] && ! echo "$syntax_validation" | grep -q "Success"; then
+      #     echo "SYNTAX ERROR was found in the given config.yml: '$syntax_validation'" >&2
+      #     exit 1
+      # fi
 
       tutor distro run-extra-commands
       tutor config save
